from __future__ import annotations

import hashlib
import json
import re
import shutil
import subprocess
from pathlib import Path

from . import __version__

_BEGIN = "<!-- openline-airlock:begin -->"
_END = "<!-- openline-airlock:end -->"


def _run(argv: list[str], cwd: Path) -> subprocess.CompletedProcess[str]:
    return subprocess.run(argv, cwd=cwd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True, check=False)


def _repo_slug(repo: Path) -> str:
    cp = _run(["git", "remote", "get-url", "origin"], repo)
    if cp.returncode != 0:
        raise RuntimeError("could not read git remote 'origin'; pass --github-repo owner/name")
    raw = cp.stdout.strip()
    patterns = [
        r"^https?://github\.com/(?P<slug>[^/]+/[^/]+?)(?:\.git)?$",
        r"^git@github\.com:(?P<slug>[^/]+/[^/]+?)(?:\.git)?$",
        r"^ssh://git@github\.com/(?P<slug>[^/]+/[^/]+?)(?:\.git)?$",
    ]
    for pattern in patterns:
        m = re.match(pattern, raw)
        if m:
            return m.group("slug")
    raise RuntimeError("origin is not a github.com repository; pass --github-repo owner/name")


def _python_dockerfile(config: dict) -> str:
    commands = []
    verification = config.get("verification", {})
    for group in ("target_commands", "static_commands", "test_commands"):
        commands.extend(verification.get(group, []))
    heads = {row[0] for row in commands if row}
    tools = []
    if "pytest" in heads:
        tools.append("pytest")
    if "ruff" in heads:
        tools.append("ruff")
    if "mypy" in heads:
        tools.append("mypy")
    extras = ""
    if tools:
        extras = "\nRUN python -m pip install --no-cache-dir " + " ".join(sorted(set(tools)))
    return (
        "# Generated by `airlock install-github`. Candidate patches cannot modify this file.\n"
        "FROM python:3.12-slim\n"
        "RUN apt-get update && apt-get install -y --no-install-recommends git ca-certificates \\\n"
        "    && rm -rf /var/lib/apt/lists/*\n"
        "WORKDIR /opt/airlock-base\n"
        "COPY . /opt/airlock-base\n"
        "RUN python -m pip install --no-cache-dir ."
        + extras
        + "\nWORKDIR /workspace\n"
    )


def _detect_runtime(repo: Path, config: dict) -> str:
    if (repo / "pyproject.toml").exists() or (repo / "setup.py").exists() or (repo / "setup.cfg").exists():
        return _python_dockerfile(config)
    raise RuntimeError(
        "GitHub Actions installation currently auto-builds Python evaluation images only. "
        "Add a maintainer-owned .airlock/Dockerfile, then rerun with --force."
    )


def _workflow() -> str:
    return """name: Airlock contributions

on:
  issue_comment:
    types: [created]

# Serialize public submissions. The queue can grow, but only one Airlock evaluation
# for this repository consumes runner compute at a time.
concurrency:
  group: airlock-${{ github.repository }}
  cancel-in-progress: false

permissions: {}

jobs:
  admit:
    if: ${{ github.event.issue.pull_request == null && startsWith(github.event.comment.body, '/airlock submit ') }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - id: admit
        name: Static admission
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          PYTHONPATH=.airlock/runtime python -m airlock_submit.actions admit --out .airlock-action
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: airlock-admission-${{ github.event.comment.id }}
          path: .airlock-action/
          if-no-files-found: error
          retention-days: 30

  evaluate:
    needs: admit
    if: ${{ needs.admit.result == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/download-artifact@v4
        with:
          name: airlock-admission-${{ github.event.comment.id }}
          path: .airlock-action
      - name: Evaluate candidate
        env:
          GITHUB_TOKEN: ""
          GH_TOKEN: ""
        run: |
          PYTHONPATH=.airlock/runtime python -m airlock_submit.actions evaluate --in .airlock-action --out .airlock-result
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: airlock-result-${{ github.event.comment.id }}
          path: .airlock-result/
          if-no-files-found: error
          retention-days: 30

  publish:
    needs: [admit, evaluate]
    if: ${{ always() && needs.admit.result == 'success' && needs.evaluate.result == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v4
        with:
          name: airlock-result-${{ github.event.comment.id }}
          path: .airlock-result
      - name: Publish Airlock result
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          PYTHONPATH=.airlock/runtime python -m airlock_submit.actions publish --in .airlock-result
"""


def _contributing_block() -> str:
    return f"""{_BEGIN}
## AI-assisted contributions

**AI agents are welcome. Raw AI-generated PRs are not.**

If an agent generated the patch, send the commit through Airlock before opening a PR.

1. Fork this repository and start from the current default branch.
2. Let any coding agent make the change, then push the commit to your public fork.
3. Copy the full commit SHA with `git rev-parse HEAD`.
4. On the issue you are fixing, comment:

```text
/airlock submit YOUR_GITHUB_USERNAME/YOUR_FORK@FULL_40_CHARACTER_COMMIT_SHA
```

Do **not** open a pull request yourself. Airlock will reply on the issue.

- `BLOCKED` — the patch failed a repository rule. No PR is opened.
- `NEEDS_EVIDENCE` — the repository does not have enough evidence to justify review yet. No PR is opened.
- `REOPEN` — the base branch moved after evaluation. Refresh the patch and submit again.
- `SURVIVED` — Airlock opens a normal PR and a maintainer reviews it like any other contribution.

No agent gets push access. No candidate decides what passing means.

Use whatever coding agent you want. **The repo decides what passes.**
{_END}
"""


def _replace_marked(text: str, block: str) -> str:
    if _BEGIN in text and _END in text:
        start = text.index(_BEGIN)
        end = text.index(_END, start) + len(_END)
        return text[:start] + block.rstrip() + text[end:]
    if text and not text.endswith("\n"):
        text += "\n"
    return text + ("\n" if text else "") + block


def _sha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _copy_runtime(repo: Path) -> list[Path]:
    package_root = Path(__file__).resolve().parent.parent
    dest_root = repo / ".airlock" / "runtime"
    if dest_root.exists():
        shutil.rmtree(dest_root)
    files = {
        "airlock": ["__init__.py", "sieve.py", "util.py"],
        "airlock_submit": ["__init__.py", "actions.py", "github_api.py", "policy.py"],
    }
    copied: list[Path] = []
    for package, names in files.items():
        src_dir = package_root / package
        dst_dir = dest_root / package
        dst_dir.mkdir(parents=True, exist_ok=True)
        for name in names:
            dst = dst_dir / name
            shutil.copy2(src_dir / name, dst)
            copied.append(dst)
    return copied


def install_github(
    repo: Path,
    *,
    github_repo: str | None = None,
    base_branch: str = "main",
    force: bool = False,
) -> dict:
    repo = repo.resolve()
    config_path = repo / ".airlock" / "config.json"
    if not config_path.exists():
        raise RuntimeError(".airlock/config.json is missing; run `airlock init` first")
    config = json.loads(config_path.read_text())
    if config.get("schema") != "airlock.config.v1":
        raise RuntimeError("unsupported .airlock/config.json schema")
    baseline = config.get("init_baseline", {})
    if not baseline.get("green"):
        raise RuntimeError("Airlock baseline is not green; fix the repo before installing the GitHub gate")

    slug = github_repo or _repo_slug(repo)
    if not re.match(r"^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$", slug):
        raise RuntimeError("GitHub repository must be owner/name")

    airlock_dir = repo / ".airlock"
    workflows = repo / ".github" / "workflows"
    airlock_dir.mkdir(parents=True, exist_ok=True)
    workflows.mkdir(parents=True, exist_ok=True)

    dockerfile_path = airlock_dir / "Dockerfile"
    if dockerfile_path.exists() and not force:
        dockerfile = dockerfile_path.read_text()
    else:
        dockerfile = _detect_runtime(repo, config)
        dockerfile_path.write_text(dockerfile)

    submit = {
        "schema": "airlock.submit.v1",
        "mode": "github-actions",
        "repo": slug,
        "base_branch": base_branch,
        "container_image": "openline-airlock-evaluator:local",
        "min_account_age_days": 7,
        "min_public_repos": 0,
        "max_daily_submissions_per_user": 5,
        "max_active_submissions": 1,
        "max_patch_files": 60,
        "max_patch_bytes": 2_000_000,
        "evaluation_timeout_seconds": 1200,
        "memory": "2g",
        "cpus": "2",
        "pids_limit": 512,
        "require_source_owner_matches_submitter": True,
    }
    submit_path = airlock_dir / "submit.json"
    submit_path.write_text(json.dumps(submit, indent=2, sort_keys=True) + "\n")

    workflow_path = workflows / "airlock.yml"
    workflow_path.write_text(_workflow())

    runtime_files = _copy_runtime(repo)

    contributing = repo / "CONTRIBUTING.md"
    old = contributing.read_text() if contributing.exists() else ""
    contributing.write_text(_replace_marked(old, _contributing_block()))

    generated = [config_path, submit_path, dockerfile_path, workflow_path, contributing, *runtime_files]
    manifest = {
        "schema": "airlock.github.install.v1",
        "airlock_version": __version__,
        "repo": slug,
        "base_branch": base_branch,
        "mode": "github-actions",
        "standing_service": False,
        "files": [
            {"path": str(path.relative_to(repo)).replace("\\", "/"), "sha256": _sha(path)}
            for path in sorted(generated)
        ],
        "security": {
            "static_protected_path_check_before_docker": True,
            "evaluation_job_has_write_permissions": False,
            "evaluation_checkout_persists_credentials": False,
            "candidate_network": "none",
            "candidate_github_credentials": False,
            "trusted_publish_job_executes_candidate_code": False,
            "repo_submission_concurrency": 1,
        },
    }
    manifest_path = airlock_dir / "github-install.json"
    manifest_path.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n")
    return {**manifest, "manifest": str(manifest_path.relative_to(repo))}
